# Generated by Django 5.0 on 2025-11-24 19:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del producto (puede ser SKU o código de barras)', max_length=50, unique=True, verbose_name='Código / Referencia')),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras para escaneo', max_length=100, null=True, verbose_name='Código de Barras')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Stock')),
                ('cantidad_minima', models.IntegerField(default=5, help_text='Alerta cuando llegue a este nivel', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Mínima')),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'Unidad'), ('DOCENA', 'Docena'), ('CAJA', 'Caja'), ('PAQUETE', 'Paquete'), ('KILO', 'Kilogramo'), ('GRAMO', 'Gramo'), ('LITRO', 'Litro'), ('METRO', 'Metro'), ('PAR', 'Par'), ('JUEGO', 'Juego')], default='UNIDAD', max_length=20, verbose_name='Unidad de Medida')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, help_text='Precio al que se compra el producto', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Compra')),
                ('estado', models.CharField(choices=[('DISPONIBLE', '🟢 Disponible'), ('POR_AGOTAR', '🟡 Por Agotarse'), ('AGOTADO', '🔴 Agotado')], default='DISPONIBLE', max_length=20, verbose_name='Estado del Producto')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar en lugar de eliminar', verbose_name='Producto Activo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
                ('ubicacion', models.CharField(blank=True, help_text='Estante, pasillo, zona, etc.', max_length=100, verbose_name='Ubicación en Bodega')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('ultima_salida', models.DateTimeField(blank=True, null=True, verbose_name='Última Salida')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='categorias.categoria', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='categorias.subcategoria', verbose_name='Subcategoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['codigo'], name='inventario__codigo_d18360_idx'), models.Index(fields=['codigo_barras'], name='inventario__codigo__f8dec9_idx'), models.Index(fields=['estado'], name='inventario__estado_7e7e86_idx')],
            },
        ),
    ]
