# Generated by Django 5.0 on 2025-11-24 19:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('SUPER_ADMIN', '👑 Super Administrador (Dueño)'), ('ADMIN', '👨\u200d💼 Administrador'), ('EMPLEADO', '👤 Empleado'), ('AUDITOR', '👁️ Auditor/Contador')], default='EMPLEADO', max_length=20, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Documento de Identidad')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/perfiles/', verbose_name='Foto de Perfil')),
                ('aprobado', models.BooleanField(default=False, help_text='El usuario debe ser aprobado por un administrador', verbose_name='Cuenta Aprobada')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('modo_oscuro', models.BooleanField(default=False, verbose_name='Modo Oscuro Activado')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
                'permissions': [('puede_aprobar_usuarios', 'Puede aprobar nuevos usuarios'), ('puede_ver_reportes', 'Puede ver reportes completos'), ('puede_eliminar_productos', 'Puede eliminar productos')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('CREAR', 'Creación de Registro'), ('EDITAR', 'Edición de Registro'), ('ELIMINAR', 'Eliminación de Registro'), ('DESCONTAR', 'Descuento de Producto'), ('EXPORTAR', 'Exportación de Reporte')], max_length=20, verbose_name='Tipo de Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Actividad',
                'verbose_name_plural': 'Historial de Actividades',
                'ordering': ['-fecha'],
            },
        ),
    ]
