# Generated by Django 5.0 on 2025-11-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='notificado_aprobacion',
            field=models.BooleanField(default=False, verbose_name='Correo de aprobación enviado'),
        ),
    ]
