# Generated by Django 5.0 on 2025-11-24 19:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AGOTADO', '🔴 Producto Agotado'), ('POR_AGOTAR', '🟡 Producto Por Agotarse'), ('REABASTECIMIENTO', '📦 Necesita Reabastecimiento')], max_length=30, verbose_name='Tipo de Alerta')),
                ('mensaje', models.TextField(verbose_name='Mensaje de Alerta')),
                ('fecha_generada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Generada')),
                ('leida', models.BooleanField(default=False, verbose_name='Alerta Leída')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('resuelta', models.BooleanField(default=False, verbose_name='Alerta Resuelta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Alerta de Inventario',
                'verbose_name_plural': 'Alertas de Inventario',
                'ordering': ['-fecha_generada'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', '📥 Entrada'), ('SALIDA', '📤 Salida'), ('AJUSTE', '⚖️ Ajuste'), ('DEVOLUCION', '↩️ Devolución')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('cantidad_anterior', models.IntegerField(default=0, verbose_name='Cantidad Anterior')),
                ('cantidad_nueva', models.IntegerField(default=0, verbose_name='Cantidad Nueva')),
                ('motivo', models.CharField(blank=True, help_text='Razón del movimiento', max_length=200, verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Realizó el Movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='movimientos_fecha_48492e_idx'), models.Index(fields=['producto', '-fecha'], name='movimientos_product_8bb7fc_idx')],
            },
        ),
    ]
